version: "3.9"
services:
  database:
    image: postgres:14.2-alpine
    env_file: .env-db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
     - pgadmin-data:/var/lib/pgadmin

  selenium:
    image: "selenium/standalone-chrome:latest"
    container_name: "selenium"
    hostname: selenium
    shm_size: '2gb'
    restart: always
    ports:
      - "4444:4444"

  web:
    build:
      context: .
      args:
        - DEV=true
    command: >
      sh -c "python source/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    depends_on:
      - selenium
      - database
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    shm_size: "2gb"
    restart: on-failure
    env_file: source/.env



volumes:
  db-data:
  pgadmin-data: