version: "3.9"
services:

  database:
    restart: always
    container_name: postgres_database
    image: postgres:14.2-alpine
    env_file: .env-db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
     - pgadmin-data:/var/lib/pgadmin

  redis:
    restart: always
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379

  app:
    restart: always
    container_name: pepper_app
    build:
      context: .
      args:
        - DEV=true
    volumes:
      - .:/app
    depends_on:
      - database
      - redis
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file: source/.env
    shm_size: 2gb
    working_dir: /source
    #command: uvicorn configuration.asgi:application --host 0.0.0.0  --reload
    #command: gunicorn --reload --bind 0.0.0.0:8000 configuration.wsgi #python manage.py runserver 0.0.0.0:8000
    command: bash -c "python3 manage.py runserver 0.0.0.0:8000"


  celery-worker:
    restart: always
    container_name: celery-worker
    build: .
    volumes:
      - .:/app
    depends_on:
      - redis
      - database
    working_dir: /source
    command: bash -c "celery -A configuration.celery worker -l info"


volumes:
  db-data:
  pgadmin-data: