# Generated by Django 4.2.7 on 2024-03-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pepper_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="successfulresponse",
            name="request_id",
            field=models.PositiveIntegerField(),
        ),
    ]
