# Generated by Django 4.2.7 on 2024-01-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pepper_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userrequest",
            name="minimum_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
    ]
