# Generated by Django 4.2.3 on 2023-11-18 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pepper_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scrapingstatistic",
            name="start_page",
        ),
    ]
