name: Run pytest unit tests

on:
  push:
    branches:
      - main  # Replace with your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Replace with your desired Python version

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run pytest
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        cd source
        pytest