---
  name: Checks

  on: [push]

  jobs:
    test-lint:
      name: Test and Lint
      runs-on: ubuntu-20.04
      defaults:
        run:
          working-directory: source/
      steps:
        - name: Configure Env
          run: |
            touch .env
            echo "${{ secrets.ENV_FILE }}" > .env
        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: "${{ secrets.DOCKERHUB_USER }}"
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Checkout
          uses: actions/checkout@v2
        - name: Test
          run: |
            echo .env
            docker-compose run --rm app sh -c "pytest"

