---
  name: Checks

  on: [push]

  jobs:
    test-lint:
      name: Test and Lint
      runs-on: ubuntu-20.04

      steps:
        - name: Configure Env
          run: |
            touch .env
            echo "${{ secrets.ENV_FILE }}" > .env
        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USER }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Checkout
          uses: actions/checkout@v2
        - name: Test
          env:
            DEBUG: ${{ secrets.DEBUG }}
            SECRET_KEY: ${{ secrets.SECRET_KEY }}
            URL: ${{ secrets.URL }}
            DATABASE_URL: ${{ secrets.DATABASE_URL }}
            ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
          run: |
            pip install -r requirements.txt
            sudo service postgresql start
            cd source
            pytest

